import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/fonts/fonts";
import MainLayout from "@/components/layouts/MainLayout";

export const metadata: Metadata = {
  title: "Phan Ngoc Trieu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-navy min-h-screen text-slate-400 tracking-widest`}
      >
        {" "}
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
